### ISSUE TITLE
Deviant drop confusion

### ISSUE THREAD

**Issue by Brendoshi** [gatheringhallstudios/MHGenDatabase#32]
Hey, ended up with some confusion in how some deviant items are gained when specifically looking for an item.

In this case, it was Dreadking carapace: http://i.imgur.com/Tapr9Jr.png

At first we assumed it was numbers for dreadking 2/3 (which would be incorrect). After checking the dreadking tab itself we noted that these were referring to the quest difficulty tiers.

Is there any possible way to update things so that it shows.

Besides capture 1/2/3, break head 1/2/3 etc, is there any other naming that'd work better? Naming them after their quest brackets might work. In dreadkings case that'd be Capture 1-4, Capture 5-8, Capture 9-10.

If not, feel free to tell me to sod off :p

**Comment by jaysondc** [comment]
Are the brackets the same for all deviant monsters?

**Comment by JosephMichels** [comment]
Yes, I believe the brackets are all the same.

I originally just called them 1/2/3 because there were 3 levels of drops and I suspected the one that was used depended on the level of the deviant quest. 

We can change to whatever if it would make more sense.

**Comment by jaysondc** [comment]
OK can you change the deviant monster names to "Dreading 1-4", "Dreading 5-8" and so on in your next DLC update?

**Comment by JosephMichels** [comment]
This has been fixed in the upcoming MHGU App.

Basically there are 3 cases that need to be considered:

* Monsters with LR + HR + G rank deviant quests (Lv1-3, Lv4-5, Lv6-8, Lv9-10, G1-2, G3-4, G5-6)
* Monsters with HR + G rank deviant quests (Lv1-4, Lv5-8, Lv9-10, G1-2, G3-4, G5-6)
* Monsters with only G rank deviant quests (G1-2, G3-4, G5-6)

They are labeled more clearly in the upcoming app.
